
### Recuperar todos las zonas de un evento
GET http://localhost:3000/api/eventZones/event/19

### Recuperar todos las zonas de un evento que no existe (404)
GET http://localhost:3000/api/eventZones/event/9999

### Recuperar los detalles para un event_zone_id
GET http://localhost:3000/api/eventZones/43

### Recuperar los detalles para un event_zone_id que no existe (404)
GET http://localhost:3000/api/eventZones/999