
### Recuperar la información de pagos, tickets y asientos para un user_id
GET http://localhost:3000/api/payments/user/14


### Recuperar la información de pagos, tickets y asientos para un user_id sin pagos asociados
GET http://localhost:3000/api/payments/user/9999